"""PlanQualityMetric — evaluates the quality of an agent's generated plan."""

from __future__ import annotations

from ..base import BaseMetric, MetricResult
from ...test_case import LLMTestCase

_PLAN_QUALITY_PROMPT = """You are evaluating the quality of a plan generated by an AI agent.

Goal / Task: {goal}
Agent's Generated Plan:
{plan}

Evaluate the quality of this plan on the following dimensions:
1. Completeness: Does the plan cover all necessary steps to achieve the goal?
2. Logical ordering: Are the steps in a sensible, dependency-aware sequence?
3. Feasibility: Are the steps actionable and realistic given the context?
4. Efficiency: Does the plan avoid unnecessary or redundant steps?
5. Clarity: Are the steps clearly described with enough detail?
6. Risk awareness: Does the plan account for potential obstacles or failure modes?

Score from 0 to 10:
- 10: Excellent plan — complete, logically ordered, feasible, efficient, and clear
- 7-9: Good plan with minor gaps or inefficiencies
- 4-6: Adequate plan but missing important steps or has ordering/clarity issues
- 1-3: Poor plan with significant gaps, illogical ordering, or infeasible steps
- 0: Plan is entirely inadequate or irrelevant to the goal

Return as JSON: {{
  "score": <0-10>,
  "strengths": ["..."],
  "weaknesses": ["..."],
  "missing_steps": ["..."],
  "reason": "..."
}}

Evaluation:"""


class PlanQualityMetric(BaseMetric):
    """
    Evaluates the quality of a plan generated by an LLM agent.

    Assesses the plan on completeness, logical ordering, feasibility,
    efficiency, clarity, and risk awareness.

    Requires: input (the goal/task), actual_output (the generated plan)
    The actual_output should contain the agent's plan as text.

    Optional: Use additional_metadata["plan_context"] to provide extra context.
    """

    def __init__(
        self,
        threshold: float = 0.5,
        model=None,
        strict_mode: bool = False,
        verbose_mode: bool = False,
    ) -> None:
        super().__init__(threshold=threshold, strict_mode=strict_mode, verbose_mode=verbose_mode)
        self._model = model

    def measure(self, test_case: LLMTestCase) -> MetricResult:
        provider = self._model or self._get_default_provider()

        raw = self._llm_judge(
            _PLAN_QUALITY_PROMPT.format(
                goal=test_case.input,
                plan=test_case.actual_output,
            ),
            provider=provider,
        )

        score_raw = self._parse_json_field(raw, "score") or 0
        strengths = self._parse_json_field(raw, "strengths") or []
        weaknesses = self._parse_json_field(raw, "weaknesses") or []
        missing = self._parse_json_field(raw, "missing_steps") or []
        reason = self._parse_json_field(raw, "reason") or raw[:200]

        score = float(score_raw) / 10.0
        passed = self._pass_fail(score)

        eval_steps = []
        if strengths:
            eval_steps.append(f"Strengths: {', '.join(strengths)}")
        if weaknesses:
            eval_steps.append(f"Weaknesses: {', '.join(weaknesses)}")
        if missing:
            eval_steps.append(f"Missing steps: {', '.join(missing)}")
        if not eval_steps:
            eval_steps = ["Plan quality evaluated."]

        self._score = score
        self._reason = reason
        self._result = MetricResult(
            score=score,
            passed=passed,
            reason=reason,
            metric_name=self.name,
            threshold=self.threshold,
            strict_mode=self.strict_mode,
            evaluation_steps=eval_steps,
            verbose_logs=raw if self.verbose_mode else None,
        )
        return self._result
